### ISSUE TITLE
CS:Go problem

### ISSUE THREAD

**Issue by wasyady** [RumbleFrog/Anti-Private#6]
I tried it, but don't wanna work for me.  :cry:
Have you got any idea for this problem ? :blush:

OS: Win2008R2

L 11/09/2017 - 13:27:17: SourceMod error session started
L 11/09/2017 - 13:27:17: Info (map "de_dust2") (file "errors_20171109.log")
L 11/09/2017 - 13:27:17: [SM] Unable to load plugin "Anti_Private.smx": Native "Steam_CreateHTTPRequest" was not found
L 11/09/2017 - 13:27:26: Error log file session closed.

SourceMod Version Information:
             SourceMod Version: 1.8.0.6032
             SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.6032)
             SourcePawn API: v1 = 4, v2 = 11
             Compiled on: Oct 22 2017 15:15:47
             Built from: https://github.com/alliedmodders/sourcemod/commit/afcd94a
             Build ID: 6032:afcd94a
             http://www.sourcemod.net/

[SM] Displaying 24 extensions:
         [01] Automatic Updater (1.8.0.6032): Updates SourceMod gamedata files
         [02] Webternet (1.8.0.6032): Extension for interacting with URLs
         [03] Accelerator (2.3.1): SRCDS Crash Handler
         [04] CS Tools (1.8.0.6032): CS extended functionality
         [05] BinTools (1.8.0.6032): Low-level C/C++ Calling API
         [06] SDK Tools (1.8.0.6032): Source SDK Tools
         [07] Client Preferences (1.8.0.6032): Saves client preference settings
         [08] MySQL-DBI (1.8.0.6032): MySQL driver implementation for DBI
         [09] DHooks (2.1.1): Dynamic Hooks
         [10] SDK Hooks (1.8.0.6032): Source SDK Hooks
         [11] Top Menus (1.8.0.6032): Creates sorted nested menus
         [12] Regex (1.8.0.6032): Provides regex natives for plugins
         [13] <FAILED> file "steamtools.ext.dll": error code 0000007e
         [14] SteamWorks Extension (1.2.2): Exposes SteamWorks functions to Developers
         [15] SMJansson (2.6.0/1): JSON parser/writer
         [16] PTaH (P Tools and Hooks) (1.0.7): Expanding sdkhooks and sdktools
         [17] <FAILED> file "connecthook.ext.dll": error code 0000007e
         [18] MessageBot (2.0): MessageBot Extension
         [19] Socket (3.0.1): Socket extension for SourceMod
         [20] GeoIP (1.8.0.6032): Geographical IP information
         [21] <FAILED> file "sendproxy.ext.dll": error code 0000007e
         [22] TAU LIB (1.1): 
         [23] cURL Extension (1.3.0.0): cURL Extension
         [24] SQLite (1.8.0.6032): SQLite Driver

[SM] Listing 76 plugins:
           01 "[CS:GO/CSS] AbNeR Round End Sounds" (3.5fix) by AbNeR_CSS
           02 "Admin all spec" (1.0.2) by Dr!fter
           03 "Admin File Reader" (1.8.0.6032) by AlliedModders LLC
           04 "Admin Help" (1.8.0.6032) by AlliedModders LLC
           05 "Admin Menu" (1.8.0.6032) by AlliedModders LLC
           06 "C4Timer CSGO" (1.5.0) by dalto, Panda
           07 "Advertisements" (2.0.2) by Tsunami
           08 "AFK Manager" (4.1.5) by Rothgar
           09 "Anti-Flood" (1.8.0.6032) by AlliedModders LLC
           10 <Failed> "Anti Private" (1.0.1) by Fishy
           11 "BanId Fix" (0.4) by SM9();
           12 "Basic Chat" (1.8.0.6032) by AlliedModders LLC
           13 "Basic Comm Control" (1.8.0.6032) by AlliedModders LLC
           14 "Basic Commands" (1.8.0.6032) by AlliedModders LLC
           15 "Basic Info Triggers" (1.8.0.6032) by AlliedModders LLC
           16 "Basic Votes" (1.8.0.6032) by AlliedModders LLC
           17 "CallAdmin" (0.1.5) by Impact, Popoklopsi
           18 "CallAdmin: Steam module" (0.1.5) by Impact, Popoklopsi
           19 "Client Preferences" (1.8.0.6032) by AlliedModders LLC
           20 "CS:GO Admin ESP" (2.1) by Root
           21 "SM CS:GO New Items" (1.1) by Franc1sco franug
           22 "CSS Bank" (1.6.6) by Miraculix
           23 "SM Franug CSGO Sprays" (1.4.2) by Franc1sco Steam: franug, EMINEM
           24 "Fast Team Balancer" (1.0.6) by [W]atch [D]ogs
           25 "[CS:GO] Fake Competitive Ranks/Coins" (1.2) by Laam4
           26 "Fun Commands" (1.8.0.6032) by AlliedModders LLC
           27 "Fun Votes" (1.8.0.6032) by AlliedModders LLC
           28 "Gloves" (1.0.1) by kgns - wasdzone
           29 "GameVoting" (1.8.7) by Neatek
           30 "[ANY] Ban Disconnected Player" (2.0) by Headline, Original Plugin : mad_hamster
           31 "High Ping Kicker - Lite Edition" (1.0.0.1) by Liam
           32 "RankMe" (3.0.3.Kento.22) by lok1, Scooby, pracc, Kento
           33 "MapChooser" (1.8.0.6032) by AlliedModders LLC
           34 "SM Most Active" (2.2) by Franc1sco Steam: franug
           35 "Nextmap" (1.8.0.6032) by AlliedModders LLC
           36 "Map Nominations" (1.8.0.6032) by AlliedModders LLC
           37 "Player Commands" (1.8.0.6032) by AlliedModders LLC
           38 "Player models by flags" (1.2) by boomix
           39 "[CSGO] QuakeSounds Overlays edition" (1.0) by TonyBaretta
           40 "RandomCycle" (1.8.0.6032) by AlliedModders LLC
           41 "Random Emptymap" (1.0) by Zipcore
           42 "Reserved Slots" (1.8.0.6032) by AlliedModders LLC
           43 "Rock The Vote" (1.8.0.6032) by AlliedModders LLC
           44 "sbp.smx"
           45 "SourceBans++: Admin Config Loader" (1.6.2) by AlliedModders LLC, SourceBans++ Dev Team
           46 "SourceBans++: Bans Checker" (1.6.2) by psychonic, Ca$h Munny, SourceBans++ Dev Team
           47 "SourceBans++: SourceComms" (1.6.2) by Alex, SourceBans++ Dev Team
           48 "SourceBans++: Main Plugin" (1.6.2) by SourceBans Development Team, SourceBans++ Dev Team
           49 "SourceBans++: SourceSleuth" (1.6.2) by ecca, SourceBans++ Dev Team
           50 "Simple Chat Processor (Redux)" (1.1.5) by Simple Plugins, Mini
           51 "SourceMod Anti-Cheat" (0.8.6.0) by SMAC Development Team
           52 "SMAC Aimbot Detector" (0.8.6.0) by SMAC Development Team
           53 "SMAC AutoTrigger Detector" (0.8.6.0) by SMAC Development Team
           54 "SMAC Client Protection" (0.8.6.0) by SMAC Development Team
           55 "SMAC Command Monitor" (0.8.6.0) by SMAC Development Team
           56 "SMAC Rcon Locker" (0.8.6.0) by SMAC Development Team
           57 "SMAC Anti-Speedhack" (0.8.6.0) by SMAC Development Team
           58 "SMAC Spinhack Detector" (0.8.6.0) by SMAC Development Team
           59 "[CSGO] Advanced Admin" (1.5.8) by PeEzZ
           60 "Bombsite Limiter" (1.2.3) by Tomasz 'anacron' Motylinski
           61 "Client Execute" (1.0.0.3) by dubbeh
           62 "SM File/Folder Downloader and Precacher" (1.4) by SWAT_88
           63 "Sound Commands" (1.8.0.6032) by AlliedModders LLC
           64 "Stealth Revived" (0.6) by SM9();
           65 "Rotate server graphic banners" (0.3) by HiTmAnY
           66 "[SWGM] Command Listener" (1.1) by Someone
           67 "Steam Works Group Manager" (1.7) by Someone
           68 "[CSGO/CSS] Chat/Scoreboard Tag Menu" (1.6.0 SCP) by [W]atch [D]ogs
           69 "csgotokens.com token changer" (1.4.5) by Adi - live4net
           70 "tVIP" (1.3) by Totenfluch
           71 "Updater" (1.2.2) by GoD-Tony
           72 "VIP Grenades on Spawn" (0.2) by shanapu
           73 "VIP Generator" (1.02) by Adi - live4net
           74 "Weapons & Knives" (1.0.11) by kgns | pluginal.com
           75 "Weapon Restrict" (3.1.7) by Dr!fter
           76 "Web Shortcuts CS:GO version" (2.4) by Franc1sco franug and James "sslice" Gray
         Errors:
         Anti_Private.smx (Anti Private): Native "Steam_CreateHTTPRequest" was not found

**Comment by rumblefrog** [comment]
Do you have either SteamWorks or SteamTools installed?

**Comment by wasyady** [comment]
Both.

[13] file "steamtools.ext.dll": error code 0000007e
[14] SteamWorks Extension (1.2.2): Exposes SteamWorks functions to Developers

But steamtools dosen't work.

**Comment by rumblefrog** [comment]
Can you uninstall SteamTools

**Comment by rumblefrog** [comment]
The plugin is attempting to use SteamTools, which according to Sourcemod, is available. Despite the fact that it's throwing errors.

**Comment by rumblefrog** [comment]
I'm going to assume this issue is resolved and go ahead and close this. If anything new comes up, I'll reopen it.

**Comment by kmsraidboss** [comment]
Commenting here to say I am receiving the same error without steamtools on the server. Game is CSGO, windows OS, have all the required extensions and they are working (using with other plugins as well). Figured it was worth mentioning that this still exists since OP has not followed up.

**Comment by wasyady** [comment]
I removed steamtools support from your plugin, and working at now.

**Comment by rumblefrog** [comment]
I've updated the SteamTools build dependency, let me know if it happens again.

**Comment by wasyady** [comment]
Okey, I will try it at today night!
